---
- name: K3S Cluster Playbook (All Nodes)
  hosts: k3s_cluster
  gather_facts: true
  roles:
    - role: base
      become: true

- name: K3S Cluster Playbook (Control Plane Nodes)
  hosts: control
  roles:
    - role: control_node
      become: true

- name: K3S Cluster Playbook (Worker Nodes)
  hosts: worker
  roles:
    - role: worker_node
      become: true

- name: K3S Cluster Playbook (Post Install - setup CRDs)
  hosts: control
  roles:
    - role: post
      become: true
