---

- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: base
      become: true
    - role: download
      become: true

- hosts: control
  roles:
    - role: k3s/control
      become: true

- hosts: worker
  roles:
    - role: k3s/worker
      become: true

- hosts: control
  roles:
    - role: k3s/post
      become: true
