---
# defaults file for control_node
server_init_args: >-
  {% if groups['control'] | length > 1 %}
    {% if ansible_hostname == hostvars[groups['control'][0]]['ansible_hostname'] %}
      --cluster-init
    {% else %}
      --server https://{{ hostvars[groups['control'][0]].k3s_node_ip | split(",") | first | ansible.utils.ipwrap }}:6443
    {% endif %}
    --token {{ k3s_token }}
  {% endif %}
  {{ extra_server_args | default('') }}
