---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Override host variables
      ansible.builtin.set_fact:
        # See: https://github.com/flannel-io/flannel/blob/67d603aaf45ef80f5dd39f43714fc5e6f8a637eb/Documentation/troubleshooting.md#Vagrant
        # noqa yaml[line-length]
        flannel_iface: eth1

        # The test VMs might be a bit slow, so we give them more time to join the cluster:
        retry_count: 25

        # Make sure that our IP ranges do not collide with those of the default scenario
        apiserver_endpoint: "192.168.56.111"
        metal_lb_ip_range: "1192.168.56.130-192.168.56.139"

    - name: "Include beer30.control_node"
      ansible.builtin.include_role:
        name: "beer30.control_node"
